language: python
# python:
#   - "2.7"
#   - "3.6"
os: # 
  - linux
  - osx
  - windows
# command to instinstall:
install:
  - pip install numpy
# commands to run test
script: 
  - python test.py
# condition
branches:
  only:
    - master

