language: minimal
matrix:
  include:
    - os: linux
      sudo: true
    - os: windows
    - os: osx
# command to instinstall:
install:
  - pip install --user -r requirements
# commands to run test
script: 
  - python test.py
# condition
branches:
  only:
    - master

# python:
#   - "2.7"
#   - "3.6"
# os: # 
#  - linux
#  - osx
#  - windows
