## ---- EXAMPLE 1:  minimal, cross platform. 
# NOTE: use --user with pip 
# language: minimal
# matrix:
#   include:
#     - os: linux
#       sudo: true
#     - os: windows
#     - os: osx
# # command to instinstall:
# install:
#   - pip install --user -r requirements.txt
# # commands to run test
# script: 
#   - python test.py
# # condition
# branches:
#   only:
#     - master

## ---- EXAMPLE 2: python
language: python
python:
  - "2.7"
  - "3.6"
os: 
 - linux
sudo: true
install:
    #  - sudo apt-get install nsis
 - pip install -r requirements.txt
# commands to run test
script: 
  - python test.py
  - echo "$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH-$TRAVIS_BUILD_ID-$TRAVIS_TAG"
  - echo "$TRAVIS_JOB_ID-$TRAVIS_JOB_NUMBER-$TRAVIS_BUILD_ID-$TRAVIS_TAG"
  - echo "$TRAVIS_TAG"
  - echo "$TRAVIS_COMMIT"

before_deploy:
  - echo "$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH-$TRAVIS_BUILD_ID-$TRAVIS_TAG"
  - echo "$TRAVIS_JOB_ID-$TRAVIS_JOB_NUMBER-$TRAVIS_BUILD_ID-$TRAVIS_TAG"
  - if [[ "$TRAVIS_TAG" == "" ]]; then export TRAVIS_TAG="dev" ; fi
  - echo "$TRAVIS_TAG"
  - echo "$TRAVIS_TAG"
  - echo "$TRAVIS_COMMIT"
  - export VERSION_NAME=`git describe | sed 's/\(.*\)-.*/\1/'`
#  - pip install pynsist
#  - make
#  - ls build/nsis/*

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
      - test.py
  overwrite:  true
  name: $VERSION_NAME
  target_commitish: $TRAVIS_COMMIT # <--------both used
  tag_name: $TRAVIS_TAG # <--------both used
  skip_cleanup: true
  on:
     tags: true
     condition: $TRAVIS_PYTHON_VERSION = 3.6
# name: Build $(date +'%d.%m.%Y %R')
# "${TRAVIS_BUILD_NUMBER}-${TRAVIS_BRANCH}-${TRAVIS_BUILD_ID}"
#- make
# deploy:
#  provider: heroku
#   api_key: ...
#   app: my-app-123
# run:
#     - "rake db:migrate"
#     - restart
#     - "rake cleanup"
# after_deploy:
#   - ./after_deploy_1.sh
#   - ./after_deploy_2.sh

# --- ENVIRONMENT VARIABLES
# user defined in yaml file:
# env:
#   global:
#     - CAMPFIRE_TOKEN=abc123
#     - TIMEOUT=1000
#  
# TRAVIS:
#  $TRAVIS_JOB_NUMBER: e.g. 37.2
