## ---- EXAMPLE 1:  minimal, cross platform
# language: minimal
# matrix:
#   include:
#     - os: linux
#       sudo: true
#     - os: windows
#     - os: osx
# # command to instinstall:
# install:
#   - pip install --user -r requirements.txt
# # commands to run test
# script: 
#   - python test.py
# # condition
# branches:
#   only:
#     - master

## ---- EXAMPLE 2: python
language: python
python:
  - "2.7"
  - "3.6"
os: 
 - linux
install:
  - sudo apt-get install nsis
  - pip install pynsist
  - pip install -r requirements.txt
# commands to run test
script: 
  - python test.py
  - make

# before_deploy: "echo 'ready?'"
# deploy:
#  provider: heroku
#   api_key: ...
#   app: my-app-123
# run:
#     - "rake db:migrate"
#     - restart
#     - "rake cleanup"
# after_deploy:
#   - ./after_deploy_1.sh
#   - ./after_deploy_2.sh
