language: python
# python:
#   - "2.7"
#   - "3.6"
#os: # 
#  - linux
#  - osx
#  - windows
matrix:
  include:
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.7"
# command to instinstall:
install:
  - pip install numpy
# commands to run test
script: 
  - python test.py
# condition
branches:
  only:
    - master

