## ---- EXAMPLE 1:  minimal, cross platform. 
# NOTE: use --user with pip 
# language: minimal
# matrix:
#   include:
#     - os: linux
#       sudo: true
#     - os: windows
#     - os: osx
# # command to instinstall:
# install:
#   - pip install --user -r requirements.txt
# # commands to run test
# script: 
#   - python test.py
# # condition
# branches:
#   only:
#     - master

## ---- EXAMPLE 2: python
language: python
python:
  - "2.7"
  - "3.6"
os: 
 - linux
sudo: true
install:
  - sudo apt-get install nsis
  - pip install -r requirements.txt
# commands to run test
script: 
  - python test.py

before_deploy:
  - pip install pynsist
  - make
  - ls dist\nsis\*

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: dist/nsis/test*.exe
  skip_cleanup: true
  on:
     condition: $TRAVIS_PYTHON_VERSION = 3.6

#- make
# deploy:
#  provider: heroku
#   api_key: ...
#   app: my-app-123
# run:
#     - "rake db:migrate"
#     - restart
#     - "rake cleanup"
# after_deploy:
#   - ./after_deploy_1.sh
#   - ./after_deploy_2.sh
